name = "RiaFst"
author = "liziluyu"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba23dd8db5813a6ef9fba90e82ac7828e0045d5e4c249093cea8a5b7b0826d98"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
