name = "RiaFst"
author = "liziluyu"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d48ec9c955825ebdec612094166ba08a80a8f5c360e6ccec2ab63f2306fe694f"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
