
#Texture of ChinjufuMod's Helmet.
[helmet_texture]
	#All=0, Without Clothes=1, Only Clothes=2
	#Range: 0 ~ 2
	Helmet_Texture = 0

#Texture of ChinjufuMod's Chestplate.
[chestplate_texture]
	#All=0, Without Clothes=1, Only Clothes=2
	#Range: 0 ~ 2
	Chestplate_Texture = 0

#Texture of ChinjufuMod's Leggings.
[leggings_texture]
	#All=0, Without Clothes=1, Only Clothes=2
	#Range: 0 ~ 2
	Leggings_Texture = 0

#Texture of ChinjufuMod's Boots.
[boots_texture]
	#All=0, Without Clothes=1, Only Clothes=2
	#Range: 0 ~ 2
	Boots_Texture = 0

