
#Ammo blast breaks the block.
[explosion]
	#Ammo blast breaks the block, when this setting is true.
	Break_Blocks = true

#Generation and chance of CherryBiome.
[biome_cherry]
	#CherryBiome will be generated, when this setting is true.
	CherryBiome_Generate = true
	#Common=9, Rare=1, Default=2
	#Range: 1 ~ 9
	CherryBiome_Chance = 2

#Generation and chance of AcerBiome.
[biome_acer]
	#AcerBiome will be generated, when this setting is true.
	AcerBiome_Generate = true
	#Common=9, Rare=1, Default=2
	#Range: 1 ~ 9
	AcerBiome_Chance = 2

#Generation and chance of GinkgoBiome.
[biome_ginkgo]
	#GinkgoBiome will be generated, when this setting is true.
	GinkgoBiome_Generate = true
	#Common=9, Rare=1, Default=2
	#Range: 1 ~ 9
	GinkgoBiome_Chance = 2

#Chestnuts fall from Autumn leaves.
[chestnuts_fall]
	#Chestnuts fall from Autumn leaves, when this setting is true.
	Chestnuts_Fall = true

#Low-processing sound on carrier-borne aircraft.
[low_sound]
	#Use a more low-processing sound on carrier-borne aircraft, when this setting is true.
	Low_Sound = false

#Use a MAKIMONO block.
[use_makimono]
	#You can use MAKIMONO block, when this setting is true.
	Use_MAKIMONO = true

